# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.


services:
  db:
    image: postgres:17
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  api:
      container_name: bd
      restart: unless-stopped
      build:
        context: .
      image: bank-card
      env_file:
        - .env
      ports:
        - "8080:8080"
      depends_on:
          - db
