spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jwt:
    secret: "${JWT_SECRET:yourSuperSecretKeyThatIsAtLeast32CharactersLong1234567890}"
    expiration: ${JWT_EXPIRATION:86400000}