--liquibase formatted sql
--changeset dlevazhinskiy:1
CREATE TABLE IF NOT EXISTS Users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_owner VARCHAR(50),
    role    VARCHAR(5)
);

--changeset dlevazhinskiy:2
CREATE TABLE IF NOT EXISTS Bank_card
(
    bank_card_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Card_holder_id BIGINT REFERENCES Users (user_id),
    expired_at     DATE,
    status         VARCHAR,
    balance        NUMERIC(12, 5)
);

-- changeset dlevazhinskiy:3
ALTER TABLE Bank_card ALTER COLUMN card_holder_id TYPE BIGINT;
ALTER TABLE Bank_card ALTER COLUMN bank_card_id TYPE BIGINT;
ALTER TABLE Users ALTER COLUMN user_id TYPE BIGINT;
