--liquibase formatted sql
--changeset dlevazhinskiy:1
CREATE TABLE IF NOT EXISTS Users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_owner    VARCHAR(50),
    role          VARCHAR(5),
    user_password VARCHAR NOT NULL
);

--changeset dlevazhinskiy:2
CREATE TABLE IF NOT EXISTS Bank_card
(
    bank_card_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_number    CHAR(16) UNIQUE NOT NULL CHECK (card_number ~ '^[0-9]{16}$'),
    Card_holder_id BIGINT REFERENCES Users (user_id),
    expired_at     DATE,
    status         VARCHAR,
    balance        NUMERIC(12, 5) DEFAULT 0.0
);

